In [125]:
import pandas as pd

In [126]:
data = {
    "Name": ["Ali", "Sara", "Ahmed","Ayesha"],
    "Age": [20, 22, 19,None],
    "City": ["Lahore", "Karachi", "Islamabad","Lahore"]
}

In [127]:
df=pd.DataFrame(data)

In [128]:
df

     Name   Age       City
0     Ali  20.0     Lahore
1    Sara  22.0    Karachi
2   Ahmed  19.0  Islamabad
3  Ayesha   NaN     Lahore

In [129]:
df.head(2)

   Name   Age     City
0   Ali  20.0   Lahore
1  Sara  22.0  Karachi

In [130]:
df.tail(1)

     Name  Age    City
3  Ayesha  NaN  Lahore

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     3 non-null      float64
 2   City    4 non-null      object
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes

In [132]:
df.shape

(4, 3)

In [133]:
df.describe()

             Age
count   3.000000
mean   20.333333
std     1.527525
min    19.000000
25%    19.500000
50%    20.000000
75%    21.000000
max    22.000000

In [134]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [135]:
df.dtypes

Name     object
Age     float64
City     object
dtype: object

In [136]:
df.count()

Name    4
Age     3
City    4
dtype: int64

In [137]:
#column Selection
df["Name"]

0       Ali
1      Sara
2     Ahmed
3    Ayesha
Name: Name, dtype: object

In [138]:
#filtring
df[df["Age"]>20]

   Name   Age     City
1  Sara  22.0  Karachi

In [139]:
df[df["City"]=="Lahore"]

     Name   Age    City
0     Ali  20.0  Lahore
3  Ayesha   NaN  Lahore

In [140]:
#Missing values
df.isnull()

    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False   True  False

In [141]:
df.isnull().sum()

Name    0
Age     1
City    0
dtype: int64

In [142]:
#remove missing value
df.dropna()

    Name   Age       City
0    Ali  20.0     Lahore
1   Sara  22.0    Karachi
2  Ahmed  19.0  Islamabad

In [143]:
#Fill missing value
df.fillna(24)

     Name   Age       City
0     Ali  20.0     Lahore
1    Sara  22.0    Karachi
2   Ahmed  19.0  Islamabad
3  Ayesha  24.0     Lahore

In [144]:
#Sorting
df.sort_values("Age")

     Name   Age       City
2   Ahmed  19.0  Islamabad
0     Ali  20.0     Lahore
1    Sara  22.0    Karachi
3  Ayesha   NaN     Lahore

In [145]:
df.sort_values("Age",ascending=False)

     Name   Age       City
1    Sara  22.0    Karachi
0     Ali  20.0     Lahore
2   Ahmed  19.0  Islamabad
3  Ayesha   NaN     Lahore

In [146]:
#Grouping
df.groupby("City").get_group("Lahore")

     Name   Age    City
0     Ali  20.0  Lahore
3  Ayesha   NaN  Lahore

In [ ]:
#Count
df.groupby("City").count()

           Name  Age
City
Islamabad     1    1
Karachi       1    1
Lahore        2    1

In [ ]:
#Size
df.groupby("City").size()

City
Islamabad    1
Karachi      1
Lahore       2
dtype: int64

In [149]:
#Mean
df.groupby("City")["Age"].mean()

City
Islamabad    19.0
Karachi      22.0
Lahore       20.0
Name: Age, dtype: float64

In [150]:
#Sum
df.groupby("City")["Age"].sum()

City
Islamabad    19.0
Karachi      22.0
Lahore       20.0
Name: Age, dtype: float64

In [151]:
#Min
df.groupby("City")["Age"].min()

City
Islamabad    19.0
Karachi      22.0
Lahore       20.0
Name: Age, dtype: float64

In [152]:
#Max
df.groupby("City")["Age"].max()

City
Islamabad    19.0
Karachi      22.0
Lahore       20.0
Name: Age, dtype: float64